"""Pydantic data models for domain entities and prediction contracts."""

from pydantic import BaseModel, Field


class IncomingMessage(BaseModel):
    """Representation of an incoming raw message row."""

    message_id: str
    user_id: str
    conversation_type: str
    group_id: str | None = None
    business_id: str | None = None
    sender_user_id: str | None = None
    created_at: str
    message_text: str = ""
    media_type: str = ""
    media_id: str | None = None
    forwarded_count: int = 0


class UserMetadata(BaseModel):
    """User profile metadata including quiet hours settings."""

    user_id: str
    quiet_hours_start: int | None = None
    quiet_hours_end: int | None = None


class GroupMemberMetadata(BaseModel):
    """Group membership settings per user."""

    user_id: str
    group_id: str
    is_muted: bool = False
    role: str = "member"


class LLMPrediction(BaseModel):
    """Unprocessed prediction contract generated by the LLM."""

    action: str
    message_type: str
    reason: str
    confidence: float = Field(default=0.85, ge=0.0, le=1.0)


class FinalOutputRow(BaseModel):
    """Schema for final output.csv row format."""

    message_id: str
    action: str
    message_type: str
    reason: str
    confidence: float
    evidence_message_ids: str = "none"