version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    ports:
      - "5000:5000"
    command: mlflow ui --host 0.0.0.0